#!/usr/bin/env python3

import sys
import ctypes

from inspect import getmembers
from pprint import pformat

x = lambda _a: pformat(getmembers(_a))

from elftools.elf.elffile import ELFFile, Section
from gen import bpf
from gen import libbpf

# NOTE: workaround for ctypesgen, that does not understand flexible struct members
class my_btf_ext_info_sec(ctypes.Structure):
     pass
my_btf_ext_info_sec._fields_ = [
    ('sec_name_off', ctypes.c_uint32),
    ('num_info', ctypes.c_uint32)
]

# NOTE:
# it should be autogenerated (as 'struct_btf_ext_header' is),
# but for some reason it's not there - define it here for now.
class workaround_struct_btf_header(ctypes.Structure):
    pass

workaround_struct_btf_header.__slots__ = ['magic', 'version', 'flags', 'hdr_len',
    'type_off', 'type_len', 'str_off', 'str_len']

workaround_struct_btf_header._fields_ = [('magic', ctypes.c_uint16), ('version', ctypes.c_uint8), (
    'flags', ctypes.c_uint8), ('hdr_len', ctypes.c_uint32),
    ('type_off', ctypes.c_uint32), ('type_len', ctypes.c_uint32), ('str_off', ctypes.c_uint32), ('str_len', ctypes.c_uint32)]


# NOTE: following is a workaround for missing 'enum' type in 'ctypes' package.
from enum import IntEnum

class workaround_enum_bpf_core_relo_kind(IntEnum):
       BPF_CORE_FIELD_BYTE_OFFSET = 0 # * field byte offset
       BPF_CORE_FIELD_BYTE_SIZE   = 1 # * field size in bytes
       BPF_CORE_FIELD_EXISTS      = 2 # * field existence in target kernel
       BPF_CORE_FIELD_SIGNED      = 3 # * field signedness (0 - unsigned, 1 - signed)
       BPF_CORE_FIELD_LSHIFT_U64  = 4 # * bitfield-specific left bitshift
       BPF_CORE_FIELD_RSHIFT_U64  = 5 # * bitfield-specific right bitshift
       BPF_CORE_TYPE_ID_LOCAL     = 6 # * type ID in local BPF object
       BPF_CORE_TYPE_ID_TARGET    = 7 # * type ID in target kernel
       BPF_CORE_TYPE_EXISTS       = 8 # * type existence in target kernel
       BPF_CORE_TYPE_SIZE         = 9 # * type size in bytes
       BPF_CORE_ENUMVAL_EXISTS    = 10 #  enum value existence in target kernel
       BPF_CORE_ENUMVAL_VALUE     = 11 #  enum value integer value
       BPF_CORE_TYPE_MATCHES      = 12 #  type match in target kernel


def get_null_terminated_str(data: bytes, first_byte_offset: int) -> str:
    return data[first_byte_offset:].split(b"\0")[0].decode("ascii")

def main():
    # Ensure a single CLI parameter is provided
    if len(sys.argv) != 2:
        print("Usage: python script.py <path-to-elf-file>")
        sys.exit(1)

    elf_path = sys.argv[1]


    def get_section_assert_exists(name: str) -> Section:
        section = elffile.get_section_by_name(name)
        if section is None:
            raise ValueError(f"Section '{name}' not found in the ELF file.")
        return section

    print(f"\n--- {elf_path} ---")


    with open(elf_path, 'rb') as f:
        elffile = ELFFile(f)

        btf_section_data : bytes = get_section_assert_exists(".BTF").data()
        btf_ext_section = get_section_assert_exists(".BTF.ext")

        btf_hdr = workaround_struct_btf_header.from_buffer_copy(btf_section_data)
        btf_hdr_len = btf_hdr.hdr_len
        assert btf_hdr_len == ctypes.sizeof(workaround_struct_btf_header)

        # probably that assert is not necessary for our relocation editor, TODO revisit
        assert btf_hdr.str_off > btf_hdr.type_off

        btf_str_data = btf_section_data[btf_hdr_len + btf_hdr.str_off:][:btf_hdr.str_len]
        btf_type_data = btf_section_data[btf_hdr_len + btf_hdr.type_off:][:btf_hdr.type_len]

        offset = btf_ext_section.header['sh_offset']
        size = btf_ext_section.header['sh_size']

        print(f"File offset: {offset}")
        print(f"Size in bytes: {size}")

        content_full = btf_ext_section.data()

        ctypes_sizeof_header = ctypes.sizeof(libbpf.struct_btf_ext_header)
        header = libbpf.struct_btf_ext_header.from_buffer_copy(content_full[:ctypes_sizeof_header])
        assert header.hdr_len == ctypes_sizeof_header
        assert header.magic == 0xeb9f

        # from docs:     /* All offsets are in bytes relative to the end of this header */
        content_after_header = content_full[ctypes_sizeof_header:]

        if header.core_relo_len == 0:
            raise ValueError("TODO no relocations (core_relo_len == 0)")
        
        import io
        stream = io.BytesIO(initial_bytes=content_after_header)
        stream.seek(header.core_relo_off)

        # reference: https://docs.kernel.org/bpf/btf.html#btf-ext-section
        core_relo_rec_size = ctypes.c_uint32.from_buffer_copy(stream.read(4)).value

        assert core_relo_rec_size == ctypes.sizeof(libbpf.struct_bpf_core_relo)

        sec_info_sizeof_partial = ctypes.sizeof(my_btf_ext_info_sec)

        struct_bpf_core_relo_instances = dict()

        # collect all known relocation types.
        while len(sec_info_partial_header_bytes := stream.read(sec_info_sizeof_partial)):
            sec_info_partial = my_btf_ext_info_sec.from_buffer_copy(sec_info_partial_header_bytes)
            corresponding_section_name = get_null_terminated_str(data=btf_str_data, first_byte_offset=sec_info_partial.sec_name_off)
            print(f"[{corresponding_section_name}] num records: {sec_info_partial.num_info}")
            
            struct_bpf_core_relo_instances[corresponding_section_name] = cur_lst = []
            for _ in range(sec_info_partial.num_info):
                record = libbpf.struct_bpf_core_relo.from_buffer_copy(stream.read(core_relo_rec_size))
                cur_lst.append(record)
                access_str_off = record.access_str_off
                access_str = btf_str_data[access_str_off:].split(b"\0")[0]
                print(f"{access_str}, type_id={hex(record.type_id)}, kind={workaround_enum_bpf_core_relo_kind(record.kind).name}")

            # TODO: leave it for convenience for now, as we deal with 'len(struct_bpf_core_relo_instances) == 1' case.
            # del cur_lst
        
        libbpf.struct_btf_type
        

if __name__ == "__main__":
    main()

