#!/usr/bin/env python3

import sys
import ctypes

from inspect import getmembers
from pprint import pformat

x = lambda _a: pformat(getmembers(_a))

from elftools.elf.elffile import ELFFile, Section
from gen import bpf
from gen import libbpf

# NOTE: workaround for ctypesgen, that does not understand flexible struct members
class my_btf_ext_info_sec(ctypes.Structure):
     pass
my_btf_ext_info_sec._fields_ = [
    ('sec_name_off', ctypes.c_uint32),
    ('num_info', ctypes.c_uint32)
]

# NOTE:
# it should be autogenerated (as 'struct_btf_ext_header' is),
# but for some reason it's not there - define it here for now.
class struct_btf_header(ctypes.Structure):
    pass

struct_btf_header.__slots__ = ['magic', 'version', 'flags', 'hdr_len',
    'type_off', 'type_len', 'str_off', 'str_len']

struct_btf_header._fields_ = [('magic', ctypes.c_uint16), ('version', ctypes.c_uint8), (
    'flags', ctypes.c_uint8), ('hdr_len', ctypes.c_uint32),
    ('type_off', ctypes.c_uint32), ('type_len', ctypes.c_uint32), ('str_off', ctypes.c_uint32), ('str_len', ctypes.c_uint32)]



def get_null_terminated_str(data: bytes, first_byte_offset: int) -> str:
    return data[first_byte_offset:].split(b"\0")[0].decode("ascii")

def main():
    # Ensure a single CLI parameter is provided
    if len(sys.argv) != 2:
        print("Usage: python script.py <path-to-elf-file>")
        sys.exit(1)

    elf_path = sys.argv[1]


    def get_section_assert_exists(name: str) -> Section:
        section = elffile.get_section_by_name(name)
        if section is None:
            raise ValueError(f"Section '{name}' not found in the ELF file.")
        return section

    print(f"\n--- {elf_path} ---")


    with open(elf_path, 'rb') as f:
        elffile = ELFFile(f)

        btf_section_data : bytes = get_section_assert_exists(".BTF").data()
        btf_ext_section = get_section_assert_exists(".BTF.ext")
        # btf_ext_section = get_section_assert_exists(".rel.BTF.ext")

        btf_hdr = struct_btf_header.from_buffer_copy(btf_section_data)
        btf_hdr_len = btf_hdr.hdr_len
        assert btf_hdr_len == ctypes.sizeof(struct_btf_header)
        btf_str_data = btf_section_data[btf_hdr_len + btf_hdr.str_off:]

        offset = btf_ext_section.header['sh_offset']
        size = btf_ext_section.header['sh_size']

        print(f"File offset: {offset}")
        print(f"Size in bytes: {size}")

        content_full = btf_ext_section.data()

        ctypes_sizeof_header = ctypes.sizeof(libbpf.struct_btf_ext_header)
        header = libbpf.struct_btf_ext_header.from_buffer_copy(content_full[:ctypes_sizeof_header])
        assert header.hdr_len == ctypes_sizeof_header
        assert header.magic == 0xeb9f

        # from docs:     /* All offsets are in bytes relative to the end of this header */
        content_after_header = content_full[ctypes_sizeof_header:]

        if header.core_relo_len == 0:
            raise ValueError("TODO no relocations (core_relo_len == 0)")
        
        import io
        stream = io.BytesIO(initial_bytes=content_after_header)
        stream.seek(header.core_relo_off)

        # reference: https://docs.kernel.org/bpf/btf.html#btf-ext-section
        core_relo_rec_size = ctypes.c_uint32.from_buffer_copy(stream.read(4)).value

        assert core_relo_rec_size == ctypes.sizeof(libbpf.struct_bpf_core_relo)

        sec_info_sizeof_partial = ctypes.sizeof(my_btf_ext_info_sec)

        while len(sec_info_partial_header_bytes := stream.read(sec_info_sizeof_partial)):
            sec_info_partial = my_btf_ext_info_sec.from_buffer_copy(sec_info_partial_header_bytes)
            corresponding_section_name = get_null_terminated_str(data=btf_str_data, first_byte_offset=sec_info_partial.sec_name_off)
            print(f"[{corresponding_section_name}] num records: {sec_info_partial.num_info}")
            
            for _ in range(sec_info_partial.num_info):
                record = libbpf.struct_bpf_core_relo.from_buffer_copy(stream.read(core_relo_rec_size))
                access_str_off = record.access_str_off
                access_str = btf_str_data[access_str_off:].split(b"\0")[0]
                print(access_str)
                # print(f"record [insn_off={hex(record.insn_off)}, type_id={record.type_id}] ({access_str_off}): {access_str}")
                # print(x(record))
            #     print(".", end="")
            # print(",", end="")
        exit(0)


        core_relo_records_num_bytes = header.core_relo_len - 4 # 4 == sizeof(core_relo_rec_size) == sizeof(u32)
        assert core_relo_records_num_bytes % core_relo_rec_size == 0
        core_relo_num_records = core_relo_records_num_bytes // core_relo_rec_size
        raise ValueError(core_relo_num_records)
        
        sec_info_lst = [libbpf.struct_btf_ext_info_sec.from_buffer_copy() for offset in range(core_relo_num_records)]

        # raise ValueError(core_relo_rec_size)
        assert ctypes.sizeof(bpf.struct_bpf_core_relo) == 16
        assert (len(content_full) - ctypes.sizeof(bpf.struct_btf_ext_header)) % 16 == 0
        
        print(content_full.decode("ascii", errors="ignore"))

if __name__ == "__main__":
    main()

